# Generated by Django 4.2.3 on 2023-07-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_poll_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
    ]
